documents = [
    {"id": 0, "content": "Deep learning models for automated cancer detection using MRI imaging.", "metadata": {"source": "paper_1"}},
    {"id": 1, "content": "Applications of machine learning in stock market forecasting.", "metadata": {"source": "paper_2"}},
    {"id": 2, "content": "Natural language processing techniques for sentiment analysis in social media.", "metadata": {"source": "paper_3"}},
    {"id": 3, "content": "Reinforcement learning for autonomous drone navigation.", "metadata": {"source": "paper_4"}},
    {"id": 4, "content": "Convolutional neural networks for object detection in real-time systems.", "metadata": {"source": "paper_5"}},
    {"id": 5, "content": "Predictive analytics in healthcare using electronic health records.", "metadata": {"source": "paper_6"}},
    {"id": 6, "content": "Transformer-based architectures for machine translation tasks.", "metadata": {"source": "paper_7"}},
    {"id": 7, "content": "Graph neural networks for social network analysis.", "metadata": {"source": "paper_8"}},
    {"id": 8, "content": "Federated learning approaches for privacy-preserving AI.", "metadata": {"source": "paper_9"}},
    {"id": 9, "content": "Explainable AI methods for transparent decision-making systems.", "metadata": {"source": "paper_10"}},

    {"id": 10, "content": "AI-driven diagnosis of cardiovascular diseases using deep learning.", "metadata": {"source": "paper_11"}},
    {"id": 11, "content": "Time-series forecasting using recurrent neural networks.", "metadata": {"source": "paper_12"}},
    {"id": 12, "content": "Image segmentation techniques for satellite imagery analysis.", "metadata": {"source": "paper_13"}},
    {"id": 13, "content": "Cybersecurity threat detection using anomaly detection algorithms.", "metadata": {"source": "paper_14"}},
    {"id": 14, "content": "Speech recognition systems powered by transformer models.", "metadata": {"source": "paper_15"}},
    {"id": 15, "content": "Energy-efficient machine learning for edge computing devices.", "metadata": {"source": "paper_16"}},
    {"id": 16, "content": "Robotics path planning using reinforcement learning algorithms.", "metadata": {"source": "paper_17"}},
    {"id": 17, "content": "Data mining techniques for large-scale genomic datasets.", "metadata": {"source": "paper_18"}},
    {"id": 18, "content": "AI-based climate change prediction models.", "metadata": {"source": "paper_19"}},
    {"id": 19, "content": "Self-supervised learning for representation learning.", "metadata": {"source": "paper_20"}},

    {"id": 20, "content": "Medical image classification using deep convolutional networks.", "metadata": {"source": "paper_21"}},
    {"id": 21, "content": "Optimization techniques in neural network training.", "metadata": {"source": "paper_22"}},
    {"id": 22, "content": "Transfer learning for low-resource NLP applications.", "metadata": {"source": "paper_23"}},
    {"id": 23, "content": "Big data analytics for smart city development.", "metadata": {"source": "paper_24"}},
    {"id": 24, "content": "Blockchain-based security frameworks for IoT systems.", "metadata": {"source": "paper_25"}},
    {"id": 25, "content": "Hybrid recommendation systems combining collaborative and content filtering.", "metadata": {"source": "paper_26"}},
    {"id": 26, "content": "AI-assisted drug discovery using generative models.", "metadata": {"source": "paper_27"}},
    {"id": 27, "content": "Emotion recognition from facial expressions using CNNs.", "metadata": {"source": "paper_28"}},
    {"id": 28, "content": "Neural architecture search for automated model design.", "metadata": {"source": "paper_29"}},
    {"id": 29, "content": "Semantic search systems powered by vector embeddings.", "metadata": {"source": "paper_30"}},

    {"id": 30, "content": "Privacy-aware machine learning in healthcare systems.", "metadata": {"source": "paper_31"}},
    {"id": 31, "content": "Real-time traffic prediction using deep neural networks.", "metadata": {"source": "paper_32"}},
    {"id": 32, "content": "AI-based fraud detection in banking systems.", "metadata": {"source": "paper_33"}},
    {"id": 33, "content": "Multimodal learning combining vision and language models.", "metadata": {"source": "paper_34"}},
    {"id": 34, "content": "Climate modeling using neural networks and satellite data.", "metadata": {"source": "paper_35"}},
    {"id": 35, "content": "Sentiment-aware chatbots using transformer models.", "metadata": {"source": "paper_36"}},
    {"id": 36, "content": "Deep reinforcement learning for game AI development.", "metadata": {"source": "paper_37"}},
    {"id": 37, "content": "Medical report summarization using NLP techniques.", "metadata": {"source": "paper_38"}},
    {"id": 38, "content": "Graph embeddings for knowledge graph completion.", "metadata": {"source": "paper_39"}},
    {"id": 39, "content": "Autonomous vehicle perception using LiDAR data.", "metadata": {"source": "paper_40"}},

    {"id": 40, "content": "Federated optimization techniques for distributed AI.", "metadata": {"source": "paper_41"}},
    {"id": 41, "content": "Neural networks for earthquake prediction modeling.", "metadata": {"source": "paper_42"}},
    {"id": 42, "content": "AI-based agricultural yield prediction systems.", "metadata": {"source": "paper_43"}},
    {"id": 43, "content": "Transfer learning in medical image segmentation.", "metadata": {"source": "paper_44"}},
    {"id": 44, "content": "Bias mitigation techniques in machine learning models.", "metadata": {"source": "paper_45"}},
    {"id": 45, "content": "Quantum machine learning algorithms for optimization problems.", "metadata": {"source": "paper_46"}},
    {"id": 46, "content": "Conversational AI systems using large language models.", "metadata": {"source": "paper_47"}},
    {"id": 47, "content": "Deep learning for wildfire detection from satellite imagery.", "metadata": {"source": "paper_48"}},
    {"id": 48, "content": "Human activity recognition using wearable sensor data.", "metadata": {"source": "paper_49"}},
    {"id": 49, "content": "Machine learning for personalized education platforms.", "metadata": {"source": "paper_50"}},

    {"id": 50, "content": "Robust anomaly detection in financial transactions.", "metadata": {"source": "paper_51"}},
    {"id": 51, "content": "Generative adversarial networks for image synthesis.", "metadata": {"source": "paper_52"}},
    {"id": 52, "content": "AI-powered recommendation systems in e-commerce.", "metadata": {"source": "paper_53"}},
    {"id": 53, "content": "Deep learning methods for protein structure prediction.", "metadata": {"source": "paper_54"}},
    {"id": 54, "content": "Knowledge distillation techniques for model compression.", "metadata": {"source": "paper_55"}},
    {"id": 55, "content": "Real-time face recognition using convolutional networks.", "metadata": {"source": "paper_56"}},
    {"id": 56, "content": "AI-based supply chain optimization models.", "metadata": {"source": "paper_57"}},
    {"id": 57, "content": "Sentiment-driven stock price prediction models.", "metadata": {"source": "paper_58"}},
    {"id": 58, "content": "Self-driving car navigation using deep reinforcement learning.", "metadata": {"source": "paper_59"}},
    {"id": 59, "content": "AI-assisted mental health monitoring systems.", "metadata": {"source": "paper_60"}},

    {"id": 60, "content": "Large-scale language models for automated text generation.", "metadata": {"source": "paper_61"}},
    {"id": 61, "content": "Energy demand forecasting using machine learning.", "metadata": {"source": "paper_62"}},
    {"id": 62, "content": "AI-powered diagnostic tools in radiology.", "metadata": {"source": "paper_63"}},
    {"id": 63, "content": "Neural network pruning for efficient inference.", "metadata": {"source": "paper_64"}},
    {"id": 64, "content": "Semantic similarity search using vector databases.", "metadata": {"source": "paper_65"}},
    {"id": 65, "content": "Reinforcement learning for smart grid management.", "metadata": {"source": "paper_66"}},
    {"id": 66, "content": "Explainable deep learning for credit risk assessment.", "metadata": {"source": "paper_67"}},
    {"id": 67, "content": "Multilingual language models for cross-lingual tasks.", "metadata": {"source": "paper_68"}},
    {"id": 68, "content": "AI-driven disease outbreak prediction models.", "metadata": {"source": "paper_69"}},
    {"id": 69, "content": "Transfer learning for medical diagnosis in low-data settings.", "metadata": {"source": "paper_70"}},

    {"id": 70, "content": "Autonomous robotics using deep Q-learning methods.", "metadata": {"source": "paper_71"}},
    {"id": 71, "content": "AI-based video surveillance systems for security.", "metadata": {"source": "paper_72"}},
    {"id": 72, "content": "Machine learning pipelines for big data processing.", "metadata": {"source": "paper_73"}},
    {"id": 73, "content": "Graph-based fraud detection in financial networks.", "metadata": {"source": "paper_74"}},
    {"id": 74, "content": "Neural text summarization techniques using transformers.", "metadata": {"source": "paper_75"}},
    {"id": 75, "content": "Federated learning for mobile healthcare applications.", "metadata": {"source": "paper_76"}},
    {"id": 76, "content": "AI-enhanced predictive maintenance in manufacturing.", "metadata": {"source": "paper_77"}},
    {"id": 77, "content": "Image classification for plant disease detection.", "metadata": {"source": "paper_78"}},
    {"id": 78, "content": "Natural language understanding for question answering systems.", "metadata": {"source": "paper_79"}},
    {"id": 79, "content": "AI-driven recommendation engines using collaborative filtering.", "metadata": {"source": "paper_80"}}
]
